# Site Settings
locale                   : "en-US"
title                    : "Chris Arderne"
author                   : "Chris Arderne"
description              : "A blog for adventurous trip reports, explorations of data and code, and sometimes even things from my day job. Use the links above to learn more, see my work and get in touch."
url                      : "https://rdrn.me"
home                     : "/"
avatar                   : "/assets/images/face.jpg" 

plugins:
  - jekyll-sitemap
  - jekyll-feed

# Reading Files
exclude:
  - .sass-cache
  - Gemfile
  - LICENSE
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

permalink: /:title/

compress_html:
  clippings: all